// <auto-generated />
using System;
using FiscalPrime.Backend.Infra.Data.PostgreSQL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FiscalPrime.Backend.Infra.Data.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSQLCrudDbContext))]
    partial class PostgreSQLCrudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("FiscalPrime.Backend.Domain.Entities.Empresas.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("CodigoCNAE")
                        .HasColumnType("text");

                    b.Property<short>("CodigoCRT")
                        .HasColumnType("smallint");

                    b.Property<int>("CodigoMunicipioIBGE")
                        .HasColumnType("int");

                    b.Property<short>("CodigoPais")
                        .HasColumnType("smallint");

                    b.Property<string>("CodigoSuframa")
                        .HasColumnType("text");

                    b.Property<short>("CodigoUF")
                        .HasColumnType("smallint");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("DataInclusao")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("DataUltimaAlteracao")
                        .HasColumnType("time");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("text");

                    b.Property<string>("InscricaoEstadualST")
                        .HasColumnType("text");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text");

                    b.Property<string>("NomePais")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("NumeroCNPJCPF")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("empresa");
                });
#pragma warning restore 612, 618
        }
    }
}
